#%RAML 0.8
title: EventNet
version: v1
baseUri: http://eventNet.com/api/v1/
mediaType: application/json
traits:
- formatable:
  queryParameters:
    format:
      description: Force the format to be returned as the format requested here. 'JSON' is only currently implemented format.
      type: string
      required: false
      example: format=json
- pagable:
  queryParameters:
    offset:
      description: Start index of elements to put in response.
      type: integer
      required: false
      example: 20
      default: 0
    limit:
      description: Number of elements in the response
      type: integer
      required: false
      example: 10
      default: 25
- geolocatable:
  queryParameters:
    latitude:
      description: The latitude of the geolocation
      type: number
      required: false
      example: 0.0
    longitude:
      description: The longitude of the geolocation
      type: number
      required: false
      example: 0.0
- searchable:
    queryParameters:
      searchTerm:
        description: The term to use in the search
        type: string
        required: false
        example: Siverstone
- userCreated:
  queryParameters:
    accessToken:
      description: The access token given to the client
      type: string
      required: true
      example: 554afa93a916a3e62a5412c81c0456aa

/events:
  description: A collection of events
  get:
    description: Return list of all events
    is : [
      formatable,
      geolocatable,
      searchable
    ]
    queryParameters:
      name:
        description: Name of event to search for
        type: string
        required: false
        example: Silverstone
      archived:
        description: Include achieved events
        type: boolean
        required: false
        example: true
        default: false
  post:
    description: Create a new event
    is: [
      geolocatable
    ]
    queryParameters:
      eventName:
        description: Name of the eventName
        type: string
        required: true
        example: O2 Arena
  /{eventID}:
    description: A item in the collection of events.
    get:
      description: Returns information about this event.
      is: [
        geolocatable
      ]
    delete:
      description: Delete this event

/posts:
  description: A collection of posts
  get:
    description: Return a list of posts
    is: [
      formatable,
      pagable,
      searchable
    ]
    queryParameters:
      eventId:
        description: The event id to load posts from
        type: integer
        required: false
        example: 1
      before:
        description: Load posts before than this date
        type: date
        required: false
        example: 2015-12-31 23:59:00
      after:
        description: Load posts after than this date
        type: date
        required: false
        example: 2015-12-31 23:59:00
      accessToken:
        description: The access token given to the client
        type: string
        required: false
        example: 554afa93a916a3e62a5412c81c0456aa
  post:
    description: Post a post in this event
    is: [
      geolocatable,
      userCreated
    ]
    queryParameters:
      eventId:
        description: The event id to load posts from
        type: integer
        required: true
        example: 1
      postContent:
        description: The content of the post
        type: string
        required: true
        example: Test post, please ignore
  /{postId}:
    description: An item in the collection of posts.
    get:
      description: Return the post
    put:
      description: Replace the post content with new content
      queryParameters:
        postContent:
          description: The content of the post
          type: string
          required: true
          example: Test post, please ignore
    delete:
      description: Deletes this post

/comments:
  description:  A collection of comments
  get:
    description: Return a list of comments
    is: [
      formatable,
      pagable,
      searchable
    ]
    queryParameters:
      postId:
        description: The post id to load comments from
        type: integer
        required: false
        example: 1
  post:
    description: Create a new comment
    is: [
      geolocatable,
      userCreated
    ]
    queryParameters:
      postId:
        description: The post id to load comments from
        type: integer
        required: true
        example: 1
      commentContent:
        description: The content of the comment
        type: string
        required: true
        example: Test comment, please ignore
  /{commentId}:
    description: An item in the collection of comments.
    get:
      description: Return the comment
    put:
      description: Replace the post content with new content
      queryParameters:
        postContent:
          description: The content of the post
          type: string
          required: true
          example: Test post, please ignore
    delete:
      description: Deletes this comment

/users:
  description: A collection of users
  get:
    description: Returns whether or not the current access token is valid
    queryParameters:
      accessToken:
        description: User access token
        type: string
        required: true
        example: 1243
  post:
    description: Create new user with parameters
    queryParameters:
      displayName:
        description: User Display name
        type: string
        required: true
        example: Joe
      icon:
        description: User icon
        type: string
        required: true
      googleId:
        description: Google ID of user
        type: integer
        required: false
        example: 1
      twitterId:
        description: Twitter ID of user
        type: integer
        required: false
        example: 1
  /{renewToken}:
    post:
      description: Request new access token

/messages:
  description:  A collection of message
  get:
    description: Return a list of messages
    is: [
      formatable,
      pagable
    ]
    queryParameters:
      eventId:
        description: The Network ID to load events from
        type: integer
        required: true
        example: 1
  post:
    description: Create a new message
    is: [
      geolocatable,
      userCreated
    ]
    queryParameters:
      eventId:
        description: The event ID that message was created on
        type: integer
        required: true
        example: 1
      messageContent:
        description: The content of the message
        type: string
        required: true
        example: Test message, please ignore
  /{messageId}:
    description: An item in the collection of messages.
    get:
      description: Return the message
    put:
      description: Replace the message content with new content
      queryParameters:
        postContent:
          description: The content of the message
          type: string
          required: true
          example: Test message, please ignore
    delete:
      description: Deletes this message

/reports:
  description: A collect of reports
  post:
    description: Report a post or a comment
    is: [
      userCreated
    ]
    queryParameters:
      postId:
        description: The post ID to report
        type: integer
        required: false
        example: 1
      commentId:
        description: The comment ID to report
        type: string
        required: true
        example: Test post, please ignore

/media:
  description: A collection of media items
  get:
    description: Return a list of media items
    queryParameters:
      postId:
        description: The post id to get media for
        type: integer
        required: true
        examlpe: 1
  post:
    description: Add a item to the list of media items. Returns the media id
  /{mediaId}:
    description: A item in the collection of media items
    get:
      description: Returns the media resource for the media item with the given id
